name: Deploy Application

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  # Для фронта: diploma-frontend, для апі: diploma-backend
  IMAGE_NAME: ${{ github.repository_owner }}/diploma-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lowercase repo name
        run: |
          # Перетворюємо весь шлях (наприклад, Maksym-Tomusiak/Diploma_API) на нижній регістр
          IMAGE_PATH=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_PATH" >> ${GITHUB_ENV}

      # ЦЕЙ КРОК КРИТИЧНИЙ ДЛЯ ORACLE ARM
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Платформа linux/arm64 для процесорів Ampere A1
          platforms: linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Авторизація в GHCR на самому сервері (робиться один раз, але безпечно повторювати)
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            cd ~/diploma
            # Оновлюємо конкретний сервіс (backend або frontend)
            docker compose pull
            docker compose up -d
            docker image prune -af
